---
title: "aa"
author: "Greta Baumilaitė"
date: "Tuesday, June 14, 2016"
output: html_document
---

1. sudarome modeli
```{r}
library(fpp)
library(car)
library(dynlm)
data=M1Germany
data
 
#a)
mod=dynlm(logm1~L(logprice,1),data)
mod
#b)
mod$res #lygties liekanos
serOrg=ts(mod$res,start=c(1960,2),frequency=4)
serOrg
#c)
plot(serOrg)

#pirmas budas
plot(stl(serOrg,s.window="periodic"))
sez=stl(serOrg,s.window="periodic")$time.series[,"seasonal"]
nesez=serOrg-sez
plot(nesez) #nesezoniniai duomenys

#antras budas
mod1=lm(serOrg~sez)
nesez2=mod1$res
plot(nesez2,type="l")

acf(nesez) #maziau lagu uzlinde uz melynos linijos
acf(nesez2)
ser=nesez


#d)
#H0:duomenys stacionarus
#H1:duomenys nestacionarus

kpss.test(ser)
#p-value=0.08198 > 0.05 H0priimame, duomenys stacionarus

#e)
plot(ser)
#is grafiko svyravimu,matosi,kad box-cox tranformacija nebus naudinga,galime patikrinti pokycius
l=BoxCox.lambda(ser)
l
plot(BoxCox(ser,l))
#pokyciai labai mazi, tad nenaudosime transformacijos


```

2.Modeliavimas
```{r}
#a
mod1=ets(ser)
#gavom ets(a,n,n)
#a-addictive errors n-no trend, n-no season
summary(mod1)
f1=forecast(mod1,h=20)
plot(f1)

#b kiti variantai
mod11=holt(ser,h=20)
plot(mod11)
mod12=holt(ser,h=20, damped=TRUE, alpha=0.7)
plot(mod12)

accuracy(mod1)
accuracy(mod11)
accuracy(mod12)
#geriausias modelis pagal RMSE mod11 , grafikas glodesnis ir tikslesnis
mod2=mod11

#c
library(forecast)
mod3=auto.arima(ser)
summary(mod3)
#gavom ARIMA(1,0,0)(1,0,0)[4], tai yra ARIMA(p,d,q)(P,D,Q)
#mazosios raides zymi nesezonine modelio dali 
#p-autoregresine modelio dalis
#d-dif eile
#q- moving average modelio dalis Didziosiso raidestas pats rik sezoniniai daliai aparsyti, [] zymi periodus per sezona, siuo atvejju 4,nes ketvirciais

#d
mod21=arima(ser,order=c(1,0,0),seasonal=list(order=c(1,0,1),perod=4))
mod22=arima(ser,order=c(1,0,2),seasonal=list(order=c(2,0,2),perod=4))
mod23=arima(ser,order=c(2,0,0),seasonal=list(order=c(2,0,1),perod=4))

accuracy(mod21)
accuracy(mod22)
accuracy(mod23)
#maziausias RMSE yra mod22
mod4=mod22

```

3.modeliu tyrimas ir palyginimas
```{r}
#a
#H0:liekanos yra baltasis triuksmas
#H1:liekanos nera baltasis triuksmas

acf(mod1$res) #tiketina bus baltasis triuksmas
Box.test(mod1$res)
#p-value=0.5571 >0.05 H0 primame

acf(mod2$res) #tiketina bus baltasis triuksmas
Box.test(mod2$res)
#p-value=0.5613 >0.05 H0 primame

acf(mod3$res) #tiketina bus baltasis triuksmas
Box.test(mod3$res)
#p-value=0.2548 >0.05 H0 primame

acf(mod4$res) #tiketina bus baltasis triuksmas
Box.test(mod4$res)
#p-value=0.9221 >0.05 H0 primame
 #visi modeliai geri,nes liekanos yra bltasis triuksmas

#b
trainset=window(ser,end=c(1985,4))
testset=window(ser, start=c(1986,1))

#c
mod31=ets(trainset,model='ANN')
mod32=holt(trainset,h=20)
mod33=auto.arima(trainset)
mod34=arima(trainset,order=c(1,0,2),seasonal=list(order=c(2,0,2),perod=4))

#d
plot(forecast(mod31))
lines(testset,col="red",lwd=3)

plot(forecast(mod32))
lines(testset,col="red",lwd=3)

plot(forecast(mod33))
lines(testset,col="red",lwd=3)

plot(forecast(mod34))
lines(testset,col="red",lwd=3)
#geriausiai atrodo mod31,mod33,mod34, nes jos prognozuoja kilima(atsizvelgiant i testset)

#e
accuracy(forecast(mod31),ser)[,2]
accuracy(forecast(mod32),ser)[,2]
accuracy(forecast(mod33),ser)[,2]
accuracy(forecast(mod34),ser)[,2]
# geriausias modelis yra mod34
modMAin=mod34
```
